//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public abstract class Apple : Component
{
	private int value
	{
		get;
		set;
	}

    protected Apple(int value, Vector position) : base(position)
    {
        this.value = value;
    }
}

 