namespace SnakeMess
{
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
    
    /// <summary>
    /// The apple.
    /// </summary>
    public abstract class Apple : Component
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Apple"/> class.
        /// </summary>
        /// <param name="value">
        /// The value.
        /// </param>
        /// <param name="position">
        /// The Position.
        /// </param>
        protected Apple(int value, Vector position) : base(position)
        {
            Value = value;
        }

        /// <summary>
        /// Gets or sets the value.
        /// </summary>
        private int Value
        {
            get; set;
        }
    }

}