namespace SnakeMess
{
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
    using System;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// The board.
    /// </summary>
    public class Board
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Board"/> class.
        /// </summary>
        /// <param name="dimension">
        /// The dimension.
        /// </param>
        /// <param name="players">
        /// The players.
        /// </param>
        public Board(Vector dimension, List<Player> players)
        {
            Dimension = dimension;
            Players = players;
            PositionSnakes();
        }

        public Board(Vector dimension, Player player)
        {
            Dimension = dimension;
            Players = new List<Player>
                          {
                              player
                          };
            this.PositionSnakes();
        }

        /// <summary>
        /// Gets the dimension.
        /// </summary>
        public Vector Dimension { get; private set; }

        public List<Apple> Apples { get; set; }

        public List<Player> Players { get; set; }

        /// <summary>
        /// The Position players.
        /// </summary>
        private void PositionSnakes()
        {
            foreach (var player in Players)
            {
                var position = new Vector();
                var direction = Direction.Right;
                switch (player.Id)
                {
                    case 1:
                        position = new Vector(Dimension.X / 4, Dimension.Y / 4);
                        direction = Direction.Right;
                        break;
                    case 2:
                        position = new Vector(Dimension.X - (Dimension.X / 4), Dimension.Y / 4);
                        direction = Direction.Left;
                        break;
                    case 3:
                        position = new Vector(Dimension.X / 4, Dimension.Y - (Dimension.Y / 4));
                        direction = Direction.Right;
                        break;
                    case 4:
                        position = new Vector(Dimension.X - (Dimension.X / 4), Dimension.Y - (Dimension.Y / 4));
                        direction = Direction.Up;
                        break;
                }
                var snake = new Snake(direction, position);
                player.Snake = snake;
            }
        }
    }
}
