namespace SnakeMess
{
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
    
    /// <summary>
    /// The component.
    /// </summary>
    public abstract class Component
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Component"/> class.
        /// </summary>
        /// <param name="position">
        /// The position.
        /// </param>
        protected Component(Vector position)
        {
            Position = position;
        }

        /// <summary>
        /// Gets or sets the Position.
        /// </summary>
        public Vector Position { get; set; }
    }
}
