//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public abstract class Component
{
	public Vector position
	{
		get;
		set;
	}

    public Component(Vector position)
    {
        this.position = position;
    }

}

