namespace SnakeMess
{
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
    
    /// <summary>
    /// The direction.
    /// </summary>
    public enum Direction
    {
        /// <summary>
        /// The up.
        /// </summary>
        Up,

        /// <summary>
        /// The down.
        /// </summary>
        Down,

        /// <summary>
        /// The left.
        /// </summary>
        Left,

        /// <summary>
        /// The right.
        /// </summary>
        Right,
    }
}
