namespace SnakeMess
{


//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
    using System.Collections.Generic;

    public class Game
    {
        private List<Player> Players { get; set; }

        private Board Board { get; set; }

    }

}