namespace SnakeMess
{
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

    /// <summary>
    /// The Collideable interface.
    /// </summary>
    public interface ICollideable
    {
        /// <summary>
        /// The is in position.
        /// </summary>
        /// <param name="location">
        /// The location.
        /// </param>
        /// <returns>
        /// The <see cref="bool"/>.
        /// </returns>
        bool IsInPosition(Vector location);
    }
}
