//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class KeyMapping
{
	private Key up
	{
		get;
		set;
	}

	private Key down
	{
		get;
		set;
	}

	private Key left
	{
		get;
		set;
	}

	private Key right
	{
		get;
		set;
	}

}

