//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Windows.Input;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;


public class KeyMapping
{
	private ConsoleKey up
	{
		get;
		set;
	}

	private ConsoleKey down
	{
		get;
		set;
	}

	private ConsoleKey left
	{
		get;
		set;
	}

	private ConsoleKey right
	{
		get;
		set;
	}

}

