namespace SnakeMess
{


//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

    using System;


    public class KeyMapping
    {
        private ConsoleKey Up { get; set; }

        private ConsoleKey Down { get; set; }

        private ConsoleKey Left { get; set; }

        private ConsoleKey Right { get; set; }

    }

}