namespace SnakeMess
{
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

    /// <summary>
    /// The move event.
    /// </summary>
    public class MoveEvent
    {
        /// <summary>
        /// Gets or sets the location.
        /// </summary>
        private Vector Location { get; set; }

        /// <summary>
        /// Gets or sets the sender.
        /// </summary>
        private SnakeComponent Sender { get; set; }
    }
}