namespace SnakeMess
{


//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
    
    public class MoveEvent
    {
        private Vector Location { get; set; }

        private SnakeComponent Sender { get; set; }

    }
}