namespace SnakeMess
{
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


    /// <summary>
    /// The player.
    /// </summary>
    public class Player
    {
        /// <summary>
        /// Gets or sets the id.
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// Gets or sets the score.
        /// </summary>
        private int Score { get; set; }

        /// <summary>
        /// Gets or sets the snake.
        /// </summary>
        private Snake Snake { get; set; }

        /// <summary>
        /// Gets or sets the key map.
        /// </summary>
        private KeyMapping KeyMap { get; set; }

        /// <summary>
        /// Initializes a new instance of the <see cref="Player"/> class.
        /// </summary>
        /// <param name="id">
        /// The id.
        /// </param>
        public Player(int id)
        {
            this.Id = id;
        }

    }
}