namespace SnakeMess
{


//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
    
    public class Player
    {
        public int Id { get; set; }

        private int Score { get; set; }

        private Snake Snake { get; set; }

        private KeyMapping KeyMap { get; set; }

        public Player(int id)
        {
            this.Id = id;
        }

    }
}