//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System; 

public class Player
{
    public int id
    {
        get;
        set;
    }

    private int score
	{
		get;
		set;
	}

	private Snake snake
	{
		get;
		set;
	}

	private KeyMapping keyMap
	{
		get;
		set;
	}

    public Player(int id)
    {
        this.id = id;
    }

}
