namespace SnakeMess
{

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

    /// <summary>
    /// The red apple.
    /// </summary>
    public class RedApple : Apple
    {
        /// <summary>
        /// The value.
        /// </summary>
        private const int Value = 10;

        public RedApple(Vector position) : base(Value, position)
        {
        }
    }
}