namespace SnakeMess
{


//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
    
    public class RedApple : Apple
    {
        private const int Value = 10;

        public RedApple(Vector position) : base(Value, position)
        {
        }
    }
}