namespace SnakeMess
{
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

    /// <summary>
    /// The snake component.
    /// </summary>
    public class SnakeComponent : Component
    {
        public SnakeComponent(Vector position, SnakePart type) : base(position)
        {
            Type = type;
        }

        /// <summary>
        /// Gets or sets the type.
        /// </summary>
        public SnakePart Type { get; private set; }
    }
}