namespace SnakeMess
{


//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
    
    public class SnakeComponent : Component
    {
        private SnakePart Type { get; set; }

        public SnakeComponent(Vector position) : base(position)
        {

        }

    }
}