namespace SnakeMess
{


//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
    using System.Collections.Generic;

    public class Snake : ICollideable
    {
        public List<SnakeComponent> Components { get; set; }

        public Player Player { get; set; }

        private Direction Direction { get; set; }

        public virtual void Move()
        {
            throw new System.NotImplementedException();
        }

        public virtual Vector GetHeadLocation()
        {
            throw new System.NotImplementedException();
        }

        public Snake()
        {
        }

        public bool IsInPosition(Vector position)
        {
            foreach (var component in Components)
            {

            }
            return true;
        }
    }
}