namespace SnakeMess
{
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
    
    public enum SnakePart
    {
        /// <summary>
        /// The head.
        /// </summary>
        Head,

        /// <summary>
        /// The tail.
        /// </summary>
        Tail,
    }
}