namespace SnakeMess
{
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
    
    public struct Vector
    {
        public int X;

        public int Y;

        public Vector(int x, int y)
        {
            this.X = x;
            this.Y = y;
        }

    }
}