//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public struct Vector
{
    public int x;

	public int y;

    public Vector(int x, int y)
    {
        this.x = x;
        this.y = y;
    }

}

