//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Vector
{
	private int x
	{
		get;
		set;
	}

	private int y
	{
		get;
		set;
	}

    public Vector() : this(0,0)
    {
    }

    public Vector(int x, int y)
    {
        this.x = x;
        this.y = y;
    }

}

