//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Player
{
	private int score
	{
		get;
		set;
	}

	private Snake snake
	{
		get;
		set;
	}

	private KeyMapping keyMap
	{
		get;
		set;
	}

    public Player(int number, KeyMapping keyMapping)
    {
        this.score = 0;
        this.snake = new Snake();
        this.snake.SetPlayer(this);
    }

}

